#verbose_logging = true

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "qed-ldap.qualcomm.com"
# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = true
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# set to true if you want to skip SSL cert validation
ssl_skip_verify = true
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

# Search user bind dn
bind_dn = "uid=omnici,ou=people,dc=qualcomm,dc=com"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = '*'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
# Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
search_filter = "(uid=%s)"

# An array of base dns to search through
search_base_dns = ["ou=people,dc=qualcomm,dc=com"]

group_search_filter = "(&(|(cn=XRResearch.gf.viewer)(cn=XRResearch.gf.admin)(cn=XRResearch.gf.editor))(member=uid=%s,ou=people,dc=qualcomm,dc=com))"
group_search_filter_user_attribute = "uid"
group_search_base_dns = ["ou=groups,dc=qualcomm,dc=com"]

# Specify names of the LDAP attributes your LDAP uses
[servers.attributes]
member_of = "dn"
email =  "qcADMailAcct"
username = "uid"
surname = "snHR"
name = "givennameHR"

[[servers.group_mappings]]
group_dn = "cn=XRResearch.gf.admin,ou=groups,dc=qualcomm,dc=com"
org_role = "Admin"
grafana_admin = true # Available in Grafana v5.3 and above
org_id = 2

#[[servers.group_mappings]]
#group_dn = "cn=XRResearch.gf.admin,ou=groups,dc=qualcomm,dc=com"
#org_role = "Admin"
#org_id = 2

[[servers.group_mappings]]
group_dn = "cn=XRResearch.gf.editor,ou=groups,dc=qualcomm,dc=com"
org_role = "Editor"
org_id = 2

[[servers.group_mappings]]
group_dn = "cn=XRResearch.gf.viewer,ou=groups,dc=qualcomm,dc=com"
org_role = "Viewer"
org_id = 2

