services:
  node_exporter:
    image: docker-registry.qualcomm.com/xrresearch/prom/node-exporter:v1.5.0
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'